name: CI/CD Pipeline

on:
  push:
    branches: [ "dev" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout deployment code
        uses: actions/checkout@v4
        with:
          repository: PashaBorovyk/pashaDemo
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops-repo

#      - name: Checkout GitOps repository
#          uses: actions/checkout@v4
#          with:
#            repository: username/my-gitops-repo
#            token: ${{ secrets.GITOPS_TOKEN }}
#            path: gitops-repo

      - name: Build and push Docker image
        run: |
          docker build -t pborovyk/pasha-app:1.4 .
          docker push pborovyk/pasha-app:1.4

      - name: Update Kubernetes manifests
        run: |
          cd gitops-repo
          
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          #NEW_TAG="1.3"
          sed -i "s|deployed-at:.*|deployed-at: \"$NOW\"|g" ks8/deployment.yaml
          #sed -i "s|image: pborovyk/pasha-app:.*|image: pborovyk/pasha-app:$NEW_TAG|g" ks8/deployment.yaml
          git add ks8/deployment.yaml
          git commit -m "Trigger ArgoCD deployment at $NOW"
          git push